# Assignment 1 — Python Fundamentals & NumPy

**Course:** Introduction to Data Science / Scientific Computing
**Topics:** Core Python, NumPy arrays, vectorization, broadcasting, linear algebra
**Total marks:** 50
**Time guideline:** 3–4 hours

---

### Instructions
1. Write your solution in the empty code cell directly **below each problem**.
2. Do **not** rename or delete the problem cells.
3. Your code must **run top to bottom without errors** (use *Kernel → Restart & Run All* before submitting).
4. Where a function is asked for, match the **exact function name and signature** given.
5. Comments explaining your logic are encouraged and count toward partial credit.
6. Submit this completed `.ipynb` file. Name it `assignment1_<your_name>.ipynb`.

> **Allowed imports:** only `numpy` (and the Python standard library). Do **not** use `pandas` for this assignment.


In [1]:
# Run this cell first
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.26.4


---
# Part A — Python Fundamentals  *(15 marks)*

No NumPy in this section. Plain Python only.

### A1. Temperature converter  *(2 marks)*

Write a function `c_to_f(celsius)` that converts a temperature in Celsius to Fahrenheit
using the formula `F = C * 9/5 + 32`.

- It should work for a single number **and** for a list of numbers (return a list in that case).

```python
c_to_f(0)          # -> 32.0
c_to_f(100)        # -> 212.0
c_to_f([0, 37, 100])  # -> [32.0, 98.6, 212.0]
```

In [2]:
# A1 — your solution here

def c_to_f(celsius):
    temp = []
    for i in celsius:
        F = i * 9/5 + 32
        temp.append(F)
    print(f'Your temperature in Fahrenheit is {temp}')
    return temp

c_to_f([0,37,100])

Your temperature in Fahrenheit is [32.0, 98.6, 212.0]


[32.0, 98.6, 212.0]

### A2. FizzBuzz with a twist  *(3 marks)*

Write a function `fizzbuzz(n)` that returns a **list** of length `n` (covering numbers `1..n`) where:
- multiples of 3 are replaced by `"Fizz"`
- multiples of 5 are replaced by `"Buzz"`
- multiples of both 3 and 5 are replaced by `"FizzBuzz"`
- all other numbers stay as integers.

```python
fizzbuzz(5)  # -> [1, 2, 'Fizz', 4, 'Buzz']
```

In [3]:
# A2 — your solution here

def fizzbuzz(n):
    num = []
    for i in range(1, n+1):
        if i%3==0 and i%5==0:
            num.append('FizzBuzz')
        elif i%3==0:
            num.append('Fizz') 
        elif i%5==0:
            num.append('Buzz')
        else:
            num.append(i)
    return num

fizzbuzz(15)


[1,
 2,
 'Fizz',
 4,
 'Buzz',
 'Fizz',
 7,
 8,
 'Fizz',
 'Buzz',
 11,
 'Fizz',
 13,
 14,
 'FizzBuzz']

### A3. Word frequency counter  *(4 marks)*

Write a function `word_count(text)` that takes a string and returns a **dictionary** mapping each
lowercase word to the number of times it appears. Ignore case and strip basic punctuation (`. , ! ?`).

```python
word_count("The cat sat. The cat ran!")
# -> {'the': 2, 'cat': 2, 'sat': 1, 'ran': 1}
```

In [4]:
# A3 — your solution here
def word_count(text):
    text= text.lower()
    
    for i in text:
        if i == "." or i == '!' or i == '?' or i == ',':
            text= text.replace(i, "")
    
    words = text.split()
    count = {}
    for i in words:
        if i in count:
            count[i] +=1
        else:
            count[i] = 1
    return count

print(word_count("The cat sat. The cat ran!"))


{'the': 2, 'cat': 2, 'sat': 1, 'ran': 1}


### A4. Filter and transform  *(3 marks)*

Given a list of integers, write a function `squares_of_evens(nums)` that returns a new list
containing the **squares of only the even numbers**, preserving order. Use a **list comprehension**.

```python
squares_of_evens([1, 2, 3, 4, 5, 6])  # -> [4, 16, 36]
```

In [5]:
# A4 — your solution here
def squares_of_evens(nums):
    new_list= []
    for i in nums:
        if i%2==0:
            new_list.append(i**2)
    return new_list

squares_of_evens([1,2,3,4,5,6,7])

[4, 16, 36]

### A5. Running maximum  *(3 marks)*

Write a function `running_max(nums)` that returns a list where the element at index `i` is the
maximum of `nums[0..i]`. Solve it with a plain loop (no NumPy, no `max()` over slices).

```python
running_max([3, 1, 4, 1, 5, 9, 2, 6])  # -> [3, 3, 4, 4, 5, 9, 9, 9]
```

In [6]:
# A5 — your solution here
def running_max(nums):
    new_list= []
    first_indice_in_list= nums[0]
    for i in nums:
        if i>first_indice_in_list:
            first_indice_in_list= i
        new_list.append(first_indice_in_list)

    return new_list

running_max([3, 1, 4, 1, 5, 9, 2, 6])

[3, 3, 4, 4, 5, 9, 9, 9]

---
# Part B — NumPy Core  *(25 marks)*

From here on, prefer **vectorized NumPy operations** over Python loops unless a loop is explicitly allowed.

### B1. Array creation  *(3 marks)*

Create and print the following arrays. Assign each to the variable name shown.

1. `a` — a 1-D array of the integers from 10 to 20 **inclusive**.
2. `b` — a 3×3 array of all ones, dtype `float`.
3. `c` — a 1-D array of 9 values **evenly spaced** between 0 and 1 (inclusive of both ends).
4. `d` — a 4×4 identity matrix.

In [7]:
# B1 — your solution here
a = np.arange(10,21)
print(f'a= {a}')

b= np.ones((3,3), dtype=float)
print(f'b= {b}')

c= np.linspace(0,1,9)
print(f'c= {c}')

d= np.eye(4)
print(f'd= {d}')

a= [10 11 12 13 14 15 16 17 18 19 20]
b= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c= [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
d= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### B2. Indexing & slicing  *(4 marks)*

Given the array `M` below, use slicing/indexing (no loops) to produce:

1. `r2` — the **third row**.
2. `last_col` — the **last column**.
3. `block` — the top-left **2×2** sub-matrix.
4. `every_other` — every other element of the **flattened** array (elements 0, 2, 4, ...).

In [8]:
M = np.arange(1, 26).reshape(5, 5)
print(M)

# B2 — your solution here
M[[2]] #Third row

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[11, 12, 13, 14, 15]])

In [9]:
M[:,4] #Last Column

array([ 5, 10, 15, 20, 25])

In [10]:
M[0:2, 0:2] #First block on the left

array([[1, 2],
       [6, 7]])

In [11]:
M.flatten()[::2] #every second element 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

### B3. Loops vs vectorization  *(4 marks)*

You are given `x = np.arange(1, 1_000_001)`.

1. Write a function `sum_of_squares_loop(x)` that computes the sum of squares using a **Python `for` loop**.
2. Write a function `sum_of_squares_vec(x)` that computes the same thing using **vectorized NumPy**.
3. Confirm both give the same result.
4. Use `%timeit` (or `time`) to compare their speed and briefly comment in a comment line on what you observe.

In [12]:
# B3.1 — your solution here
x = np.arange(1, 1_000_001)

def sum_of_squares_loop(x):
    sum=0
    for i in x:
        sum += int(i)**2
    return sum

sum_of_squares_loop(x)


333333833333500000

In [13]:
# B3.2 — your solution here
x = np.arange(1, 1_000_001)

def sum_of_squares_vec(x):
    return np.sum(x**2)
    

sum_of_squares_vec(x)

-143234976

In [14]:
# B3.3 — your solution here

loop_result = sum_of_squares_loop(x)
vec_result = sum_of_squares_vec(x)

print(loop_result)
print(vec_result)

333333833333500000
-143234976


In [15]:
# B3.4 — your solution here
%timeit sum_of_squares_loop(x)
%timeit sum_of_squares_vec(x)  #Vectorized Numpy is solving at much higher speed whereas for loop takes nearly 200 times more 

457 ms ± 32 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2 ms ± 133 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### B4. Aggregations along an axis  *(4 marks)*

Given a 2-D array `scores` of shape (5 students, 4 subjects):

1. `student_avg` — each student's average score (length-5 array).
2. `subject_max` — the highest score in each subject (length-4 array).
3. `top_student` — the **index** of the student with the highest total.
4. `overall_std` — the standard deviation of all scores.

In [16]:
rng = np.random.default_rng(42)
scores = rng.integers(40, 101, size=(5, 4))
print(scores)
print()

# B4 — your solution here
print('Results:')
#1. Student Avg
avg = np.mean(scores, axis=1) # axis=1 means along the row- we have 4 subjects (so we have to consider a row)
print(avg)
print()

#2. Subject Max
sub_max = np.max(scores, axis =0) #axis=0 means along the column
print(sub_max)
print()

#3. Top student
top_student = np.argmax(np.sum(scores, axis=1)) # np.argmax returns the index maximum value in numpy array
print(top_student)
print()

#4. Overall std
std_scores= np.std(scores)
print(std_scores)

[[45 87 79 66]
 [66 92 45 82]
 [52 45 72 99]
 [84 86 83 87]
 [71 47 91 67]]

Results:
[69.25 71.25 67.   85.   69.  ]

[84 92 91 99]

3

17.11461363864227


### B5. Boolean masking  *(4 marks)*

Using the `scores` array from B4:

1. `passing` — a boolean array, `True` where score >= 60.
2. `num_passing` — total count of passing scores.
3. `high_scores` — a 1-D array of all scores strictly greater than 90.
4. Replace every score below 50 with 50 (a "grade floor"), storing the result in `floored` **without modifying** `scores`.

In [17]:
# B5 — your solution here
print('Results:   ')
print()

#1. Passing Boolean
passing= scores>=60
print(passing)
print()

#2. total count
count= np.sum(passing)
print(count)
print()

#3. high score
high= scores[scores>90]
print(high)
print()

#4. Floored
floored = np.where(scores<50,50,scores)  # means keep 50 where scores<50 and otherwise use original scores
print(floored)
print()

Results:   

[[False  True  True  True]
 [ True  True False  True]
 [False False  True  True]
 [ True  True  True  True]
 [ True False  True  True]]

15

[92 99 91]

[[50 87 79 66]
 [66 92 50 82]
 [52 50 72 99]
 [84 86 83 87]
 [71 50 91 67]]



### B6. Reshaping & broadcasting  *(3 marks)*

1. Take `np.arange(12)` and reshape it into a 3×4 array called `grid`.
2. Create a 1-D array `col_weights = np.array([1, 2, 3, 4])` and multiply each **column** of `grid`
   by the corresponding weight using **broadcasting** (no loops). Store as `weighted`.
3. Subtract the **row mean** from each element so every row of `centered` has mean 0.

In [18]:
# B6 — your solution here

#1. Reshaping
A= np.arange(12)
A
grid= A.reshape(3,4)
grid


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
#2. Broadcasting for multiplication
col_weights = np.array([1, 2, 3, 4])
weighted = grid*col_weights
print("Weighted\n", weighted)

Weighted
 [[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]]


In [20]:
#3. Row mean subtraction
row_mean= np.mean(grid, axis=1, keepdims=True) # keepdims=True makes the means a column vector 

centered= grid-row_mean

print("Row Means:\n", row_mean)
print("\nCentered\n", centered)

print('\nRow means of centered', np.mean(centered, axis=1))

Row Means:
 [[1.5]
 [5.5]
 [9.5]]

Centered
 [[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]

Row means of centered [0. 0. 0.]


### B7. Linear algebra  *(3 marks)*

Solve the system of linear equations:

```
2x +  y -  z =  8
-3x - y + 2z = -11
-2x + y + 2z =  -3
```

1. Build the coefficient matrix `A` and the right-hand side vector `b`.
2. Solve for `[x, y, z]` using `np.linalg.solve` and store as `solution`.
3. Verify by computing `A @ solution` and comparing to `b` (use `np.allclose`).

In [21]:
# B7 — your solution here

#1.coefficient matrix
A= np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
B= np.array([8,-11,-3])

#2. solution
solution= np.linalg.solve(A, B)
print(solution)
print()

#3. Verification
verify= np.allclose(A@solution, B)
print(verify)

[ 2.  3. -1.]

True


---
# Part C — Applied Mini-Problem  *(10 marks)*

### C1. Monte Carlo estimate of π  *(6 marks)*

You can estimate π by throwing random darts at a unit square `[0,1] x [0,1]` and counting how many
land inside the quarter circle of radius 1 centered at the origin. The fraction inside, times 4,
approximates π.

Write a function `estimate_pi(n, seed=0)` that:
1. Generates `n` random `(x, y)` points in the unit square using a seeded `np.random.default_rng`.
2. Counts how many fall inside the quarter circle (`x**2 + y**2 <= 1`) — **vectorized, no loops**.
3. Returns the estimate of π as a float.

Then call it with `n = 1_000_000` and print your estimate alongside `np.pi`.

In [22]:
# C1 — your solution here
import numpy as np

def estimate_pi(n, seed=0):
    #  Initialize the seeded random number generator
    rng = np.random.default_rng(seed)

    #  Generate n random coordinates for x and y between 0 and 1
    x= rng.random(n)
    y= rng.random(n)

    #  Use the quarter circle condition to create a boolean mask
    inside_quater_circle= (x**2+ y**2) <=1

    pi_estimate= 4*np.mean(inside_quater_circle)

    return pi_estimate

# calling the function
estimated_pi_1= estimate_pi(100000)
estimated_pi_2= estimate_pi(500000)
estimated_pi_3= estimate_pi(1000000)
estimated_pi_4= estimate_pi(10000000)

print(f'Estimated pi_1 for n=100000', {estimated_pi_1})
print(f'\nEstimated pi_2 for n=500000', {estimated_pi_2})
print(f'\nEstimated pi_3 for n=1000000', {estimated_pi_3})
print(f'\nEstimated pi_4 for n=10000000', {estimated_pi_4})
print(f'\nNumpy Estimated pi', {np.pi})
print(f'\nDifferences', {np.pi-estimated_pi_1}, {np.pi-estimated_pi_2}, {np.pi-estimated_pi_3}, {np.pi-estimated_pi_4})

Estimated pi_1 for n=100000 {3.14464}

Estimated pi_2 for n=500000 {3.140584}

Estimated pi_3 for n=1000000 {3.141368}

Estimated pi_4 for n=10000000 {3.1421564}

Numpy Estimated pi {3.141592653589793}

Differences {-0.0030473464102067638} {0.0010086535897930737} {0.00022465358979317784} {-0.0005637464102070666}


### C2. Short reflection  *(4 marks)*

In the markdown cell below, answer in 3–5 sentences:

1. Why is the vectorized NumPy version in B3 so much faster than the Python loop?
2. How does the accuracy of your π estimate in C1 change as `n` grows, and why?

*Write your answer here (double-click to edit).*

1. **In vectorized Numpy version the work/array operation is done in highly optimized C code instead of python & it uses contiguous memory blocks. And talking about Python loop for every iteration is read the next element, check the data type, execute python bytecode, manage memory and it happens millions of times.**

2. **As 'n' grows the estimate of pi in C1 grows closer to pi, increasing the sample size improves the estimate as larger sample size produce small error. But it is not always the case as we can see that with n=1000000 estimate_pi_3 provides better result than with n=10000000 estimate_pi_4.**

---
### Before you submit — checklist
- [ ] Restart kernel and *Run All* — no errors.
- [ ] All function names and signatures match the spec exactly.
- [ ] No use of `pandas`; only `numpy` and the standard library.
- [ ] File renamed to `assignment1_<your_name>.ipynb`.

*Good luck!*